
server:
    port: 80
mybatis:
    mapper-locations: classpath:mapper\*.xml

spring:
    devtools:
        restart:
            additional-paths: src/main/java
            enabled: true
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: 'root'
        password: '8848'
        url: 'jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false'
