
host: "smtp.163.net"
port: 25
from: 15305067103@163.com
pass: "HDOBGLXJAHUYXDZD"
sercet: '420817abedd1fc6873ad94293887a61a'
appID: 'wxd830318512a0f826'
output: '@project.baseUri@/compiler'
input:  '@project.baseUri@/compiler'
server:
    port: 25565
mybatis:
    mapper-locations: classpath:mapper\*.xml

spring:
    profiles:
        active: 'testlocal'
    devtools:
        restart:
            additional-paths: src/main/java
            enabled: true
    datasource:
        driver-class-name: 'com.mysql.cj.jdbc.Driver'
        username: 'root'
        password: "8848"
        url: "jdbc:mysql://127.0.0.1:3306/forkluogu?useUnicode=true&characterEncoding=UTF-8"
logging:
    file:
        name: logs/log
