
server:
    port: 80
mybatis:
    mapper-locations: classpath:mapper\*.xml

spring:
    devtools:
        restart:
            additional-paths: src/main/java
            enabled: true
    datasource:
        driver-class-name: 'com.mysql.cj.jdbc.Driver'
        username: 'root'
        password: '8848xc8848'
        url: 'jdbc:mysql://124.221.237.233:3306/forkluogu?serverTimezone=UTC'
logging:
    file:
        name: log
