package com.application.model;

public class Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.user_id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.Num
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    private Long num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.describle
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    private String describle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.name
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    private Long name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.tag
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    private Integer tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.img_url
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.text
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    private String text;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.user_id
     *
     * @return the value of goods.user_id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.user_id
     *
     * @param userId the value for goods.user_id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.Num
     *
     * @return the value of goods.Num
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public Long getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.Num
     *
     * @param num the value for goods.Num
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public void setNum(Long num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.describle
     *
     * @return the value of goods.describle
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public String getDescrible() {
        return describle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.describle
     *
     * @param describle the value for goods.describle
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public void setDescrible(String describle) {
        this.describle = describle == null ? null : describle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.name
     *
     * @return the value of goods.name
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public Long getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.name
     *
     * @param name the value for goods.name
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public void setName(Long name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.tag
     *
     * @return the value of goods.tag
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public Integer getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.tag
     *
     * @param tag the value for goods.tag
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public void setTag(Integer tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.img_url
     *
     * @return the value of goods.img_url
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.img_url
     *
     * @param imgUrl the value for goods.img_url
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.text
     *
     * @return the value of goods.text
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.text
     *
     * @param text the value for goods.text
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }
}