package com.application.model;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.send_id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    private Long sendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.revice_id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    private Long reviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.number
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    private Long number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.send_id
     *
     * @return the value of message.send_id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public Long getSendId() {
        return sendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.send_id
     *
     * @param sendId the value for message.send_id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public void setSendId(Long sendId) {
        this.sendId = sendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.revice_id
     *
     * @return the value of message.revice_id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public Long getReviceId() {
        return reviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.revice_id
     *
     * @param reviceId the value for message.revice_id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public void setReviceId(Long reviceId) {
        this.reviceId = reviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.number
     *
     * @return the value of message.number
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public Long getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.number
     *
     * @param number the value for message.number
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public void setNumber(Long number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}