package com.application.model;

import java.math.BigDecimal;

public class Orders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.user_id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.goods_list
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    private String goodsList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.total_price
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    private BigDecimal totalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.state
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.addr
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    private String addr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.user_id
     *
     * @return the value of orders.user_id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.user_id
     *
     * @param userId the value for orders.user_id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.goods_list
     *
     * @return the value of orders.goods_list
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public String getGoodsList() {
        return goodsList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.goods_list
     *
     * @param goodsList the value for orders.goods_list
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public void setGoodsList(String goodsList) {
        this.goodsList = goodsList == null ? null : goodsList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.total_price
     *
     * @return the value of orders.total_price
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.total_price
     *
     * @param totalPrice the value for orders.total_price
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.state
     *
     * @return the value of orders.state
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.state
     *
     * @param state the value for orders.state
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.addr
     *
     * @return the value of orders.addr
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.addr
     *
     * @param addr the value for orders.addr
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }
}