package com.application.model;

public class shopCar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcar.id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcar.user_id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcar.goods_id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    private Long goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcar.num
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    private Integer num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcar.id
     *
     * @return the value of shopcar.id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcar.id
     *
     * @param id the value for shopcar.id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcar.user_id
     *
     * @return the value of shopcar.user_id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcar.user_id
     *
     * @param userId the value for shopcar.user_id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcar.goods_id
     *
     * @return the value of shopcar.goods_id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcar.goods_id
     *
     * @param goodsId the value for shopcar.goods_id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcar.num
     *
     * @return the value of shopcar.num
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcar.num
     *
     * @param num the value for shopcar.num
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public void setNum(Integer num) {
        this.num = num;
    }
}