package com.application.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.pass_wrod
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    private String passWrod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.wx_id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    private String wxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.imge_url
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    private String imgeUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.pass_wrod
     *
     * @return the value of user.pass_wrod
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public String getPassWrod() {
        return passWrod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.pass_wrod
     *
     * @param passWrod the value for user.pass_wrod
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public void setPassWrod(String passWrod) {
        this.passWrod = passWrod == null ? null : passWrod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.wx_id
     *
     * @return the value of user.wx_id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public String getWxId() {
        return wxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.wx_id
     *
     * @param wxId the value for user.wx_id
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public void setWxId(String wxId) {
        this.wxId = wxId == null ? null : wxId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.imge_url
     *
     * @return the value of user.imge_url
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public String getImgeUrl() {
        return imgeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.imge_url
     *
     * @param imgeUrl the value for user.imge_url
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    public void setImgeUrl(String imgeUrl) {
        this.imgeUrl = imgeUrl == null ? null : imgeUrl.trim();
    }
}