package com.application.mapper;

import com.application.model.entity.Problem;
import com.application.model.entity.ProblemExample;
import com.application.model.entity.ProblemWithBLOBs;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface ProblemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    int countByExample(ProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    int deleteByExample(ProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    int insert(ProblemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    int insertSelective(ProblemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    List<ProblemWithBLOBs> selectByExampleWithBLOBs(ProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    List<Problem> selectByExample(ProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    ProblemWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    int updateByExampleSelective(@Param("record") ProblemWithBLOBs record, @Param("example") ProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") ProblemWithBLOBs record, @Param("example") ProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    int updateByExample(@Param("record") Problem record, @Param("example") ProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    int updateByPrimaryKeySelective(ProblemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(ProblemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    int updateByPrimaryKey(Problem record);
}