package com.application.mapper;

import com.application.model.shopCar;
import com.application.model.shopCarExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface shopCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcar
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    int countByExample(shopCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcar
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    int deleteByExample(shopCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcar
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcar
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    int insert(shopCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcar
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    int insertSelective(shopCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcar
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    List<shopCar> selectByExample(shopCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcar
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    shopCar selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcar
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    int updateByExampleSelective(@Param("record") shopCar record, @Param("example") shopCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcar
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    int updateByExample(@Param("record") shopCar record, @Param("example") shopCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcar
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    int updateByPrimaryKeySelective(shopCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcar
     *
     * @mbggenerated Mon Jun 06 15:42:11 CST 2022
     */
    int updateByPrimaryKey(shopCar record);
}