package com.application.model.entity;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.gmt_create
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    private Long gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.gmt_modified
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    private Long gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.problem_id
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    private Long problemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.like
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    private Long like;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.gmt_create
     *
     * @return the value of comment.gmt_create
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.gmt_create
     *
     * @param gmtCreate the value for comment.gmt_create
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.gmt_modified
     *
     * @return the value of comment.gmt_modified
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.gmt_modified
     *
     * @param gmtModified the value for comment.gmt_modified
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.problem_id
     *
     * @return the value of comment.problem_id
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public Long getProblemId() {
        return problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.problem_id
     *
     * @param problemId the value for comment.problem_id
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public void setProblemId(Long problemId) {
        this.problemId = problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.like
     *
     * @return the value of comment.like
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public Long getLike() {
        return like;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.like
     *
     * @param like the value for comment.like
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public void setLike(Long like) {
        this.like = like;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}