package com.application.model.entity;

public class ProblemWithBLOBs extends Problem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.background
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    private String background;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.description
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.in_format
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    private String inFormat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.out_format
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    private String outFormat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.example
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    private String example;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.background
     *
     * @return the value of problem.background
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public String getBackground() {
        return background;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.background
     *
     * @param background the value for problem.background
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public void setBackground(String background) {
        this.background = background == null ? null : background.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.description
     *
     * @return the value of problem.description
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.description
     *
     * @param description the value for problem.description
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.in_format
     *
     * @return the value of problem.in_format
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public String getInFormat() {
        return inFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.in_format
     *
     * @param inFormat the value for problem.in_format
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public void setInFormat(String inFormat) {
        this.inFormat = inFormat == null ? null : inFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.out_format
     *
     * @return the value of problem.out_format
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public String getOutFormat() {
        return outFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.out_format
     *
     * @param outFormat the value for problem.out_format
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public void setOutFormat(String outFormat) {
        this.outFormat = outFormat == null ? null : outFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.example
     *
     * @return the value of problem.example
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public String getExample() {
        return example;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.example
     *
     * @param example the value for problem.example
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public void setExample(String example) {
        this.example = example == null ? null : example.trim();
    }
}