package com.application.model.entity;

public class Problem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.id
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.gmt_create
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    private Long gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.gmt_modified
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    private Long gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.user_id
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.title
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.tag
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    private Long tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.level
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    private String level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.id
     *
     * @return the value of problem.id
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.id
     *
     * @param id the value for problem.id
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.gmt_create
     *
     * @return the value of problem.gmt_create
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.gmt_create
     *
     * @param gmtCreate the value for problem.gmt_create
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.gmt_modified
     *
     * @return the value of problem.gmt_modified
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.gmt_modified
     *
     * @param gmtModified the value for problem.gmt_modified
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.user_id
     *
     * @return the value of problem.user_id
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.user_id
     *
     * @param userId the value for problem.user_id
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.title
     *
     * @return the value of problem.title
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.title
     *
     * @param title the value for problem.title
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.tag
     *
     * @return the value of problem.tag
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public Long getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.tag
     *
     * @param tag the value for problem.tag
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public void setTag(Long tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.level
     *
     * @return the value of problem.level
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.level
     *
     * @param level the value for problem.level
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }
}