package com.application.model.entity;

public class Record {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.id
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.gmt_create
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    private Long gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.gmt_modified
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    private Long gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.user_id
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.problem_id
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    private Long problemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.socre
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    private Long socre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.code
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.id
     *
     * @return the value of record.id
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.id
     *
     * @param id the value for record.id
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.gmt_create
     *
     * @return the value of record.gmt_create
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.gmt_create
     *
     * @param gmtCreate the value for record.gmt_create
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.gmt_modified
     *
     * @return the value of record.gmt_modified
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.gmt_modified
     *
     * @param gmtModified the value for record.gmt_modified
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.user_id
     *
     * @return the value of record.user_id
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.user_id
     *
     * @param userId the value for record.user_id
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.problem_id
     *
     * @return the value of record.problem_id
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public Long getProblemId() {
        return problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.problem_id
     *
     * @param problemId the value for record.problem_id
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public void setProblemId(Long problemId) {
        this.problemId = problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.socre
     *
     * @return the value of record.socre
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public Long getSocre() {
        return socre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.socre
     *
     * @param socre the value for record.socre
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public void setSocre(Long socre) {
        this.socre = socre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.code
     *
     * @return the value of record.code
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.code
     *
     * @param code the value for record.code
     *
     * @mbggenerated Tue Jun 07 15:56:47 CST 2022
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }
}