package com.application.model.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Sign {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.id
     *
     * @mbggenerated Thu Jun 09 11:26:28 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.yes
     *
     * @mbggenerated Thu Jun 09 11:26:28 CST 2022
     */
    private String yes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.no
     *
     * @mbggenerated Thu Jun 09 11:26:28 CST 2022
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.time
     *
     * @mbggenerated Thu Jun 09 11:26:28 CST 2022
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.type
     *
     * @mbggenerated Thu Jun 09 11:26:28 CST 2022
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.id
     *
     * @return the value of sign.id
     *
     * @mbggenerated Thu Jun 09 11:26:28 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.id
     *
     * @param id the value for sign.id
     *
     * @mbggenerated Thu Jun 09 11:26:28 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.yes
     *
     * @return the value of sign.yes
     *
     * @mbggenerated Thu Jun 09 11:26:28 CST 2022
     */
    public String getYes() {
        return yes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.yes
     *
     * @param yes the value for sign.yes
     *
     * @mbggenerated Thu Jun 09 11:26:28 CST 2022
     */
    public void setYes(String yes) {
        this.yes = yes == null ? null : yes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.no
     *
     * @return the value of sign.no
     *
     * @mbggenerated Thu Jun 09 11:26:28 CST 2022
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.no
     *
     * @param no the value for sign.no
     *
     * @mbggenerated Thu Jun 09 11:26:28 CST 2022
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.time
     *
     * @return the value of sign.time
     *
     * @mbggenerated Thu Jun 09 11:26:28 CST 2022
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.time
     *
     * @param time the value for sign.time
     *
     * @mbggenerated Thu Jun 09 11:26:28 CST 2022
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.type
     *
     * @return the value of sign.type
     *
     * @mbggenerated Thu Jun 09 11:26:28 CST 2022
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.type
     *
     * @param type the value for sign.type
     *
     * @mbggenerated Thu Jun 09 11:26:28 CST 2022
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}